//! clauditor-detector: Rule engine for anomaly detection
//! 
//! Stateless rule matching against events, produces alerts.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use thiserror::Error;

pub mod rules;

/// Severity levels for alerts
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// An event captured from the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Event {
    pub ts: DateTime<Utc>,
    pub kind: EventKind,
    pub pid: Option<u32>,
    pub uid: Option<u32>,
    pub session: Option<String>,
}

/// Types of events we capture
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EventKind {
    Exec { cmd: String, cwd: Option<String> },
    FileWrite { path: String },
    FileDelete { path: String },
    FileOpen { path: String },
}

/// An alert generated by the detector
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub severity: Severity,
    pub rule_id: String,
    pub description: String,
    pub event: Event,
    pub ts: DateTime<Utc>,
}

impl Alert {
    pub fn new(severity: Severity, rule_id: &str, description: &str, event: Event) -> Self {
        Self {
            severity,
            rule_id: rule_id.to_string(),
            description: description.to_string(),
            event,
            ts: Utc::now(),
        }
    }
}

#[derive(Error, Debug)]
pub enum DetectorError {
    #[error("Failed to load rules: {0}")]
    RulesLoadError(String),
    #[error("Invalid pattern: {0}")]
    InvalidPattern(String),
}

/// Main detector that runs rules against events
pub struct Detector {
    rules: Vec<rules::Rule>,
}

impl Detector {
    pub fn new() -> Self {
        Self {
            rules: rules::default_rules(),
        }
    }

    pub fn from_rules(rules: Vec<rules::Rule>) -> Self {
        Self { rules }
    }

    /// Analyze an event and return any alerts
    pub fn analyze(&self, event: &Event) -> Vec<Alert> {
        self.rules
            .iter()
            .filter_map(|rule| rule.check(event))
            .collect()
    }
}

impl Default for Detector {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_detector_creation() {
        let detector = Detector::new();
        assert!(!detector.rules.is_empty());
    }
}
